version: '3.8'

services:
  forgot:
    build:
      context: ./Frontend/forgot
    ports:
      - "8005:80"
    networks:
      - app-network

  login:
    build:
      context: ./Frontend/login
    ports:
      - "8006:80"
    networks:
      - app-network

  signup:
    build:
      context: ./Frontend/signup
    ports:
      - "8007:80"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=auth_db
      - DB_PASSWORD=admin123
      - DB_PORT=5432
      - FRONTEND_URL=http://51.20.3.185:8005
    volumes:
      - ./Backend:/app
      - ./Backend/server.env:/app/server.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: ["./wait-for-postgres.sh", "node", "server.js"]

  postgres:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
